#!/opt/homebrew/bin/python3
"""Daily proactive surfacing — find novel entity connections from recent activity."""

import json
import sys
from datetime import UTC, datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from cli_llm import dispatch  # 2026-04-17: migrated from openclaw_dispatch

INSIGHTS_DIR = Path("/Users/chrischo/server/knowledge/distilled/insights")

PROMPT = """Chris's brain has detected these hot entities from the last 7 days and their recent connections. Identify 2-3 NOVEL insights worth surfacing to Chris today.

Hot entities: {entities}

Recent connections: {connections}

Return strict JSON: {{"insights": [{{"title": "...", "description": "...", "entities": [...]}}]}}
"""


def find_hot_entities(limit: int = 10) -> list[dict]:
    """Query Neo4j for most-accessed entities in last 7 days."""
    try:
        from neo4j_client import run_query

        cutoff = (datetime.now(UTC) - timedelta(days=7)).isoformat()
        rows = run_query(
            "MATCH (e:Entity) "
            "WHERE e.last_seen_at >= $cutoff "
            "RETURN e.name AS name, e.entity_type AS type, e.mention_count AS count "
            "ORDER BY count DESC LIMIT $limit",
            {"cutoff": cutoff, "limit": limit},
        )
        return rows
    except Exception as e:
        print(f"Neo4j query failed: {e}")
        return []


def find_connections(entity_name: str, limit: int = 5) -> list[dict]:
    """Find entities recently co-mentioned with this one."""
    try:
        from neo4j_client import run_query

        rows = run_query(
            "MATCH (e:Entity {name: $name})-[r:RELATES_TO]->(other:Entity) "
            "WHERE r.co_occurrence_count >= 2 "
            "RETURN other.name AS name, other.entity_type AS type, r.weight AS weight "
            "ORDER BY r.weight DESC LIMIT $limit",
            {"name": entity_name, "limit": limit},
        )
        return rows
    except Exception:
        return []


def main():
    hot = find_hot_entities(limit=10)
    if not hot:
        print("No hot entities found")
        return 0

    connections = {}
    for entity in hot[:5]:
        name = entity.get("name", "")
        if not name:
            continue
        connections[name] = find_connections(name)

    # Dispatch to Jenna for insight extraction
    entities_str = json.dumps(hot, default=str)
    connections_str = json.dumps(connections, default=str)
    prompt = PROMPT.format(entities=entities_str, connections=connections_str)

    # 2026-04-17: migrated to cli_dispatch for stateless, sub-backed calls
    from cli_llm import cli_dispatch

    result = cli_dispatch(prompt, backend="codex", timeout=60)
    if not result.ok:
        print(f"Dispatch failed: {result.error}")
        return 1

    # Parse
    text = result.text.strip()
    if text.startswith("```"):
        text = text.split("```", 2)[1]
        if text.startswith("json"):
            text = text[4:]
        if "```" in text:
            text = text.split("```", 1)[0]

    try:
        parsed = json.loads(text.strip())
    except json.JSONDecodeError:
        print("Failed to parse insights")
        return 1

    insights = parsed.get("insights", [])
    if not insights:
        print("No new insights today")
        return 0

    # Write to file with JSON frontmatter so search_memory.collect_notes() picks it up
    today = datetime.now().strftime("%Y-%m-%d")
    INSIGHTS_DIR.mkdir(parents=True, exist_ok=True)
    out_file = INSIGHTS_DIR / f"{today}.md"

    now_iso = datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    all_entities: list[str] = []
    for insight in insights:
        for e in insight.get("entities", []) or []:
            if e and e not in all_entities:
                all_entities.append(e)

    metadata = {
        "id": f"dist_insights_{today.replace('-', '_')}",
        "type": "distilled",
        "domain": "chris",
        "subtype": "proactive_insights",
        "title": f"Daily Insights — {today}",
        "status": "active",
        "visibility": "private",
        "confidence": 0.7,
        "created_at": now_iso,
        "updated_at": now_iso,
        "last_reviewed_at": now_iso,
        "owner": "chris",
        "scope": "global",
        "valid_from": now_iso,
        "valid_to": None,
        "sources": [],
        "provenance_summary": "Auto-generated by proactive_linker from Neo4j entity co-occurrence.",
        "entities": all_entities,
        "relations": [],
        "review_state": "proposed",
        "change_policy": "review_required",
        "supersedes": [],
        "superseded_by": None,
    }

    body_lines = [f"# Daily Insights — {today}", ""]
    for i, insight in enumerate(insights, 1):
        body_lines.append(f"## {i}. {insight.get('title', 'Untitled')}")
        body_lines.append("")
        body_lines.append(insight.get("description", ""))
        body_lines.append("")
        entities = insight.get("entities", [])
        if entities:
            body_lines.append(f"**Entities:** {', '.join(entities)}")
            body_lines.append("")

    out_file.write_text(
        "---json\n" + json.dumps(metadata, indent=2, ensure_ascii=False) + "\n---\n" + "\n".join(body_lines)
    )

    print(f"Wrote {len(insights)} insights to {out_file}")

    # Notify via dispatch (goes through gateway + circuit breaker + usage tracking)
    try:
        dispatch(
            agent="jenna",
            message=f"{len(insights)} new brain insights for today ({today}). Top: {insights[0].get('title', '?')}",
            thinking="off",
            timeout=30,
        )
    except Exception:
        pass

    return 0


if __name__ == "__main__":
    sys.exit(main())
