#!/usr/bin/env python3
"""migrate_claude_memory.py — one-time migration of Claude Code auto-memory
into brain's atoms truth layer.

Reads every .md file under ~/.claude/projects/-Users-chrischo/memory/ (skipping
MEMORY.md itself, which is the index), parses the YAML frontmatter, and POSTs
each entry to /memory. The endpoint handles embedding + Chroma write + atom
mirror + supersession classification automatically.

Post-migration, MEMORY.md becomes a derived cache regenerated by
claude_memory_regen.py from the atoms layer on every SessionEnd (60s throttled),
so local edits roundtrip through brain.

Usage:
  cli/migrate_claude_memory.py            # dry run, prints what would happen
  cli/migrate_claude_memory.py --apply    # actually POST to /memory

Idempotent: re-running uses /memory's built-in dedup (NOOP on identical content).
The migration log at logs/claude_memory_migration.json captures what was sent
so we can roll back via restore_claude_memory.py if needed.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
import urllib.error
import urllib.request
from datetime import UTC, datetime
from pathlib import Path

# /memory POST is rate-limited to 30/minute. Sleep this long between POSTs
# so we never blow the limit even on re-runs after a partial.
RATE_LIMIT_SLEEP_S = 2.2

MEMORY_DIR = Path.home() / ".claude" / "projects" / "-Users-chrischo" / "memory"
BRAIN_URL = "http://127.0.0.1:8791"
SECRET_FILE = Path.home() / ".brain" / "credentials" / ".personal_webhook_secret"
MIGRATION_LOG = Path("/Users/chrischo/server/brain/logs/claude_memory_migration.json")

# Frontmatter `type` → brain category (MemoryCreateRequest enum)
TYPE_TO_CATEGORY = {
    "feedback": "preference",
    "project": "fact",
    "user": "fact",
    "reference": "entity",
    "decision": "decision",
    "preference": "preference",
    "fact": "fact",
}


def _load_secret() -> str:
    try:
        return SECRET_FILE.read_text().strip()
    except OSError:
        return ""


def _parse_frontmatter(text: str) -> tuple[dict, str]:
    """Parse YAML frontmatter between --- lines. Returns (meta, body)."""
    if not text.startswith("---"):
        return {}, text.strip()
    end = text.find("\n---", 3)
    if end < 0:
        return {}, text.strip()
    header = text[3:end].strip()
    body = text[end + 4 :].strip()
    meta: dict[str, str] = {}
    for line in header.splitlines():
        line = line.strip()
        if not line or ":" not in line:
            continue
        k, _, v = line.partition(":")
        meta[k.strip()] = v.strip().strip("\"'")
    return meta, body


def _post_memory(content: str, category: str, source: str, secret: str) -> dict:
    req = urllib.request.Request(
        f"{BRAIN_URL}/memory",
        data=json.dumps(
            {
                "content": content,
                "category": category,
                "agent": "claude",
                "source": source,
            }
        ).encode(),
        headers={
            "Authorization": f"Bearer {secret}",
            "Content-Type": "application/json",
            "x-agent": "claude",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            body = resp.read().decode()
            return {"status": "ok", "code": resp.status, "body": json.loads(body)}
    except urllib.error.HTTPError as e:
        return {"status": "http_error", "code": e.code, "body": e.read().decode()[:500]}
    except Exception as e:
        return {"status": "error", "error": str(e)[:500]}


MAX_CONTENT = 1900  # /memory POST has 2000-char limit on content field


def _compose_content(meta: dict, body: str, filename: str) -> str:
    """Combine frontmatter name + description + body into the memory content so
    the embedding captures all three signals."""
    parts = []
    name = meta.get("name") or Path(filename).stem.replace("_", " ")
    desc = meta.get("description") or ""
    if name:
        parts.append(f"# {name}")
    if desc:
        parts.append(desc)
    if body:
        parts.append(body)
    return "\n\n".join(parts)


def _chunk_content(content: str, max_chars: int = MAX_CONTENT) -> list[str]:
    """Split content into <=max_chars chunks on paragraph boundaries. Each
    chunk starts fresh but overlaps with a ~200-char preamble from the header
    so context isn't lost.

    Small inputs (<=max_chars) return a single-element list unchanged."""
    if len(content) <= max_chars:
        return [content]

    # Find the header (everything up to the first blank line) so we can
    # prepend it to each chunk for context continuity.
    lines = content.split("\n")
    header_lines: list[str] = []
    body_start = 0
    for i, line in enumerate(lines):
        if line.strip():
            header_lines.append(line)
        else:
            body_start = i + 1
            break
    header = "\n".join(header_lines).strip()
    remainder = "\n".join(lines[body_start:]).strip()
    header_prefix = f"{header}\n\n" if header else ""
    overhead = len(header_prefix) + 20  # rough padding for "(part N/M)"

    chunks: list[str] = []
    cursor = 0
    budget_per_chunk = max_chars - overhead
    while cursor < len(remainder):
        end = min(cursor + budget_per_chunk, len(remainder))
        # Back off to a paragraph boundary if possible
        if end < len(remainder):
            split = remainder.rfind("\n\n", cursor + 200, end)
            if split != -1:
                end = split
        chunks.append(remainder[cursor:end].strip())
        cursor = end
    # Prepend header + part marker to each chunk (except 1/1 which skips the marker)
    total = len(chunks)
    out: list[str] = []
    for i, chunk in enumerate(chunks, 1):
        marker = "" if total == 1 else f" (part {i}/{total})"
        out.append(f"{header_prefix}{chunk}{marker}"[:max_chars])
    return out


def _category_for(meta: dict, filename: str) -> str:
    """Map frontmatter type → brain category. Fall back to filename prefix."""
    t = (meta.get("type") or "").lower()
    if t in TYPE_TO_CATEGORY:
        return TYPE_TO_CATEGORY[t]
    lowered = filename.lower()
    if lowered.startswith("feedback_"):
        return "preference"
    if lowered.startswith("project_"):
        return "fact"
    if lowered.startswith("user_"):
        return "fact"
    if lowered.startswith("openclaw"):
        return "fact"
    return "other"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Migrate Claude Code auto-memory .md files into brain atoms."
    )
    parser.add_argument("--apply", action="store_true", help="Actually POST to /memory (default: dry run)")
    parser.add_argument("--verbose", action="store_true", help="Print each file as it's processed")
    args = parser.parse_args()

    if not MEMORY_DIR.exists():
        print(f"no auto-memory directory at {MEMORY_DIR}", file=sys.stderr)
        return 1

    secret = _load_secret() if args.apply else ""
    if args.apply and not secret:
        print("credentials missing; cannot POST", file=sys.stderr)
        return 1

    # Collect files
    files = sorted(p for p in MEMORY_DIR.glob("*.md") if p.name != "MEMORY.md")
    if not files:
        print("no .md files to migrate (excluding MEMORY.md)", file=sys.stderr)
        return 1

    log_entries: list[dict] = []
    sent = 0
    failed = 0
    skipped = 0
    for path in files:
        try:
            text = path.read_text()
        except OSError as e:
            print(f"skip {path.name}: read error {e}", file=sys.stderr)
            skipped += 1
            continue
        meta, body = _parse_frontmatter(text)
        content = _compose_content(meta, body, path.name)
        chunks = _chunk_content(content)
        category = _category_for(meta, path.name)
        base_source = f"claude_auto_memory:{path.name}"

        for idx, chunk in enumerate(chunks, 1):
            chunk_source = base_source if len(chunks) == 1 else f"{base_source}#{idx}"
            content_hash = hashlib.sha256(chunk.encode()).hexdigest()[:16]
            entry = {
                "file": path.name,
                "chunk": f"{idx}/{len(chunks)}",
                "category": category,
                "source": chunk_source,
                "content_hash": content_hash,
                "content_len": len(chunk),
                "meta_name": meta.get("name", ""),
                "ts": datetime.now(UTC).isoformat(timespec="seconds"),
            }

            if args.verbose or not args.apply:
                print(
                    f"{'[DRY]' if not args.apply else '[POST]'} {path.name:45s} chunk={idx}/{len(chunks)} category={category:11s} len={len(chunk):5d}"
                )

            if args.apply:
                result = _post_memory(chunk, category, chunk_source, secret)
                entry["result"] = result
                if result.get("status") == "ok":
                    sent += 1
                else:
                    failed += 1
                    print(
                        f"FAIL {path.name} ({idx}/{len(chunks)}): {result.get('body', result)[:200]}",
                        file=sys.stderr,
                    )
                # Pacing guard — stay under /memory 30/minute rate limit even on re-runs
                time.sleep(RATE_LIMIT_SLEEP_S)

            log_entries.append(entry)

    if args.apply:
        MIGRATION_LOG.parent.mkdir(parents=True, exist_ok=True)
        MIGRATION_LOG.write_text(
            json.dumps(
                {
                    "ts": datetime.now(UTC).isoformat(timespec="seconds"),
                    "files_total": len(files),
                    "sent": sent,
                    "skipped": skipped,
                    "entries": log_entries,
                },
                indent=2,
            )
        )
        print(f"\nMigration complete: {sent}/{len(files)} sent, log: {MIGRATION_LOG}")
    else:
        print(f"\nDry run: {len(files)} files would be migrated. Re-run with --apply to commit.")

    return (
        0 if (not args.apply or sent == len([e for e in log_entries if e.get("content_len", 0) > 0])) else 2
    )


if __name__ == "__main__":
    sys.exit(main())
