#!/Users/chrischo/server/brain/.venv/bin/python
"""cli/skill_sync.py — reconcile Brain-generated skills with Hermes profiles.

OpenClaw was retired on 2026-05-23. This script no longer mutates
``~/.openclaw/openclaw.json`` or OpenClaw per-agent skill allowlists. Hermes
loads skills from profile-local ``skills/`` directories, so Brain's active
responsibility is:

  - inspect generated skills across all Hermes profile skill directories;
  - keep a brain-owned telemetry sidecar for audit/usage tracking;
  - expose compatibility functions used by skill_materializer/openclaw_dispatch.

The historical function names are preserved to avoid a flag-day rename across
Brain jobs, but their semantics are Hermes-current.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Iterator
from datetime import UTC, datetime
from pathlib import Path

USER_HOME = Path("/Users/chrischo")
HERMES_PROFILES_ROOT = USER_HOME / ".hermes" / "profiles"
HERMES_PROFILE_NAMES = ("jenna", "liz", "ellie", "sage", "market")
HERMES_PROFILE_SKILLS_DIRS = {
    profile: HERMES_PROFILES_ROOT / profile / "skills" for profile in HERMES_PROFILE_NAMES
}
_DEFAULT_SKILLS_DIR = HERMES_PROFILE_SKILLS_DIRS["liz"]
SKILLS_DIR = HERMES_PROFILE_SKILLS_DIRS["liz"]

BRAIN_LOGS = Path("/Users/chrischo/server/brain/logs")
TELEMETRY_PATH = BRAIN_LOGS / "skill_telemetry.json"

BRAIN_PREFIX = "brain-learned-"
AUTO_PREFIX = "auto-"

_FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def _now_iso() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds").replace("+00:00", "Z")


def _parse_frontmatter_fields(block: str) -> dict[str, str]:
    """Parse the small YAML subset used by SKILL.md frontmatter."""

    fields: dict[str, str] = {}
    lines = block.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.startswith((" ", "\t")) or ":" not in line:
            i += 1
            continue
        key, _, raw_val = line.partition(":")
        key = key.strip()
        val = raw_val.strip()
        if val in {"|", ">"}:
            i += 1
            parts: list[str] = []
            while i < len(lines) and (lines[i].startswith((" ", "\t")) or not lines[i].strip()):
                parts.append(lines[i].strip())
                i += 1
            fields[key] = (" ".join(p for p in parts if p)).strip()
            continue
        if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
            val = val[1:-1]
        fields[key] = val
        i += 1
    return fields


def _parse_listish(value: str) -> list[str]:
    value = (value or "").strip()
    if not value:
        return []
    try:
        parsed = json.loads(value)
        if isinstance(parsed, list):
            return [str(item) for item in parsed if str(item)]
    except json.JSONDecodeError:
        pass
    return [part.strip().strip("'\"") for part in value.strip("[]").split(",") if part.strip()]


def hermes_profile_skill_dirs() -> dict[str, Path]:
    """Return Hermes profile skill roots, honoring legacy SKILLS_DIR patches."""
    dirs = dict(HERMES_PROFILE_SKILLS_DIRS)
    if SKILLS_DIR != _DEFAULT_SKILLS_DIR or dirs.get("liz") == _DEFAULT_SKILLS_DIR:
        dirs["liz"] = SKILLS_DIR
    return {profile: dirs[profile] for profile in HERMES_PROFILE_NAMES if profile in dirs}


def _read_skill_meta(skill_dir: Path) -> dict | None:
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        return None
    try:
        text = skill_md.read_text(encoding="utf-8")
    except OSError:
        return None
    m = _FRONTMATTER_RE.match(text)
    if not m:
        return None
    fields = _parse_frontmatter_fields(m.group(1))
    name = fields.get("name") or skill_dir.name
    description = fields.get("description", "").strip()
    auto_generated = fields.get("auto_generated", "").strip().lower() in {"true", "1", "yes"}
    brain_procedure_id = fields.get("brain_procedure_id", "").strip()
    brain_domain = fields.get("brain_domain", "").strip()
    target_profiles = _parse_listish(fields.get("target_profiles", ""))
    materialized_for = _parse_listish(fields.get("materialized_for", ""))

    meta_path = skill_dir / "_meta.json"
    if meta_path.exists():
        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
            auto_generated = auto_generated or bool(meta.get("autoGenerated"))
            brain_procedure_id = brain_procedure_id or str(meta.get("brainProcedureId") or "")
            brain_domain = brain_domain or str(meta.get("brainDomain") or "")
            target_profiles = target_profiles or [str(p) for p in meta.get("targetProfiles") or []]
            materialized_for = materialized_for or [str(p) for p in meta.get("materializedFor") or []]
        except (OSError, json.JSONDecodeError):
            pass

    return {
        "name": name,
        "description": description[:400],
        "path": str(skill_dir),
        "auto_generated": auto_generated,
        "brain_procedure_id": brain_procedure_id,
        "brain_domain": brain_domain,
        "target_profiles": target_profiles,
        "materialized_for": materialized_for,
    }


def _load_telemetry() -> dict:
    if not TELEMETRY_PATH.exists():
        return {}
    try:
        return json.loads(TELEMETRY_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def _save_telemetry(data: dict) -> None:
    TELEMETRY_PATH.parent.mkdir(parents=True, exist_ok=True)
    rendered = json.dumps(data, indent=2, ensure_ascii=False, sort_keys=True)
    tmp = TELEMETRY_PATH.with_suffix(".tmp.skill_sync")
    tmp.write_text(rendered + "\n", encoding="utf-8")
    tmp.replace(TELEMETRY_PATH)


def _iter_skill_dirs(root: Path | None = None) -> Iterator[tuple[str, Path]]:
    roots = {"liz": root} if root is not None else hermes_profile_skill_dirs()
    for profile, skill_root in roots.items():
        if not skill_root.exists():
            continue
        for child in sorted(skill_root.iterdir()):
            if child.is_dir() and not child.name.startswith("_"):
                yield profile, child


def _merge_disk_skill(disk_skills: dict[str, dict], profile: str, meta: dict) -> None:
    name = meta["name"]
    existing = disk_skills.setdefault(
        name,
        {
            "name": name,
            "description": meta.get("description", ""),
            "path": meta.get("path", ""),
            "paths": {},
            "profiles": [],
            "auto_generated": False,
            "brain_procedure_id": "",
            "brain_domain": "",
            "target_profiles": [],
            "materialized_for": [],
        },
    )
    existing["paths"][profile] = meta["path"]
    if profile not in existing["profiles"]:
        existing["profiles"].append(profile)
    # Prefer liz as the compatibility single path, then the first deterministic profile.
    if profile == "liz" or not existing.get("path"):
        existing["path"] = meta["path"]
    existing["description"] = existing.get("description") or meta.get("description", "")
    existing["auto_generated"] = bool(existing.get("auto_generated") or meta.get("auto_generated"))
    existing["brain_procedure_id"] = existing.get("brain_procedure_id") or meta.get("brain_procedure_id", "")
    existing["brain_domain"] = existing.get("brain_domain") or meta.get("brain_domain", "")
    for key in ("target_profiles", "materialized_for"):
        values = list(existing.get(key) or [])
        for value in meta.get(key) or []:
            if value not in values:
                values.append(value)
        existing[key] = values


def reconcile_registry(*, dry_run: bool = False) -> dict:
    """Reconcile Hermes profile skill files with Brain's telemetry sidecar."""

    telemetry = _load_telemetry()
    disk_skills: dict[str, dict] = {}
    for profile, child in _iter_skill_dirs() or ():
        meta = _read_skill_meta(child)
        if meta is not None:
            _merge_disk_skill(disk_skills, profile, meta)

    added_tel = 0
    updated_tel = 0
    for name, meta in disk_skills.items():
        t = telemetry.get(name)
        if t is None:
            telemetry[name] = {
                "description": meta["description"],
                "path": meta["path"],
                "paths": meta.get("paths", {}),
                "profiles": sorted(meta.get("profiles", [])),
                "auto_generated": meta.get("auto_generated", False),
                "brain_procedure_id": meta.get("brain_procedure_id", ""),
                "brain_domain": meta.get("brain_domain", ""),
                "target_profiles": meta.get("target_profiles", []),
                "materialized_for": meta.get("materialized_for", []),
                "registered_at": _now_iso(),
                "last_used_at": None,
                "use_count": 0,
                "runtime": "hermes",
            }
            added_tel += 1
            continue
        changed = False
        for key in (
            "description",
            "path",
            "paths",
            "profiles",
            "auto_generated",
            "brain_procedure_id",
            "brain_domain",
            "target_profiles",
            "materialized_for",
        ):
            if meta.get(key) is not None and t.get(key) != meta.get(key):
                t[key] = meta.get(key)
                changed = True
        if t.get("runtime") != "hermes":
            t["runtime"] = "hermes"
            changed = True
        t.setdefault("registered_at", _now_iso())
        t.setdefault("last_used_at", None)
        t.setdefault("use_count", 0)
        if changed:
            updated_tel += 1

    removed = 0
    profile_roots = tuple(str(root) for root in hermes_profile_skill_dirs().values())
    for name in list(telemetry.keys()):
        t = telemetry.get(name, {})
        if not isinstance(t, dict):
            continue
        paths = t.get("paths")
        if isinstance(paths, dict):
            changed = False
            for profile, path_claim in list(paths.items()):
                if str(path_claim).startswith(profile_roots) and not Path(str(path_claim)).exists():
                    paths.pop(profile, None)
                    changed = True
            if changed:
                t["paths"] = paths
                t["profiles"] = sorted(paths)
                if paths:
                    t["path"] = paths.get("liz") or next(iter(paths.values()))
                    updated_tel += 1
                else:
                    telemetry.pop(name, None)
                    removed += 1
                continue
        path_claim = str(t.get("path", ""))
        if path_claim.startswith(profile_roots) and not Path(path_claim).exists():
            telemetry.pop(name, None)
            removed += 1

    if not dry_run:
        _save_telemetry(telemetry)

    return {
        "registry_added": 0,
        "telemetry_added": added_tel,
        "telemetry_updated": updated_tel,
        "scrubbed_legacy": 0,
        "removed": removed,
        "total_on_disk": len(disk_skills),
        "total_entries": len(telemetry),
        "profiles": sorted(hermes_profile_skill_dirs()),
        "dry_run": dry_run,
    }


def _is_brain_generated_skill(name: str, telemetry_entry: dict) -> bool:
    if name.startswith(BRAIN_PREFIX):
        return True
    if not name.startswith(AUTO_PREFIX):
        return False
    return bool(telemetry_entry.get("auto_generated") or telemetry_entry.get("brain_procedure_id"))


def attach_generated_skills(*, dry_run: bool = False) -> dict:
    """Compatibility no-op.

    Hermes profiles discover skills from disk. No per-agent allowlist mutation is
    needed here; return generated count for audit parity with the retired path.
    """

    telemetry = _load_telemetry()
    generated_skill_names = sorted(
        n for n, t in telemetry.items() if isinstance(t, dict) and _is_brain_generated_skill(n, t)
    )
    return {
        "attached": 0,
        "agents_touched": [],
        "generated_skills_registered": len(generated_skill_names),
        "profiles": sorted(hermes_profile_skill_dirs()),
        "dry_run": dry_run,
    }


def attach_brain_skills(*, dry_run: bool = False) -> dict:
    return attach_generated_skills(dry_run=dry_run)


def bump_agent_usage(agent_name: str) -> dict:
    """Stamp generated-skill usage for a Hermes profile agent."""

    profile_dirs = hermes_profile_skill_dirs()
    if agent_name not in profile_dirs:
        return {"ok": False, "reason": "agent_not_found", "agent": agent_name}
    telemetry = _load_telemetry()
    now = _now_iso()
    bumped = 0
    for skill_name, t in telemetry.items():
        if not isinstance(t, dict) or not _is_brain_generated_skill(skill_name, t):
            continue
        paths = t.get("paths")
        if isinstance(paths, dict):
            if agent_name not in paths:
                continue
        else:
            path_claim = Path(str(t.get("path", "")))
            try:
                if not path_claim.is_relative_to(profile_dirs[agent_name]):
                    continue
            except ValueError:
                continue
        t["last_used_at"] = now
        t["use_count"] = int(t.get("use_count") or 0) + 1
        bumped += 1
    if bumped:
        try:
            _save_telemetry(telemetry)
        except Exception as exc:
            return {"ok": False, "reason": f"write_failed: {exc}", "bumped": bumped}
    return {"ok": True, "bumped": bumped, "agent": agent_name}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--bump-agent", help="stamp last_used_at for generated skills on one Hermes profile")
    args = parser.parse_args()

    if args.bump_agent:
        out = bump_agent_usage(args.bump_agent)
        print(json.dumps(out, indent=2))
        return 0 if out.get("ok") else 1

    print("[1/2] Reconciling Hermes profile skill telemetry...")
    reg = reconcile_registry(dry_run=args.dry_run)
    print(json.dumps(reg, indent=2))

    print("\n[2/2] Checking generated skill discoverability...")
    att = attach_generated_skills(dry_run=args.dry_run)
    print(json.dumps(att, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
